version: '3.8'

services:
  tinygpt-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET_KEY=your-super-secret-jwt-key-change-in-production
      - OPENWEATHER_API_KEY=your-openweather-api-key
      - NEWS_API_KEY=your-news-api-key
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data: